name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Gradle
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle

      - name: Create Gradle Build File
        run: |
          echo 'plugins { kotlin("js") version "1.8.0" }' > build.gradle.kts
          echo 'repositories { mavenCentral() }' >> build.gradle.kts
          echo 'kotlin { js { browser { } } }' >> build.gradle.kts  # FÃ¼ge browser-Zielkonfiguration hinzu

      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p public
          cp -r build/distributions/* public
          cd public
          git init
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
